parameters:
#    jira_vacuum.example.class: Jira\VacuumBundle\Example

services:
  requester:
    class: Jira\VacuumBundle\DependencyInjection\Requester
    arguments: ["https://space.atwix.com/jira/"]
